### PR TITLE
initdb.exe now accepts locale arg from ctor. Fixes issue #7

### PR DESCRIPTION
**Pull request by erikljung**

### CODE REVIEW

**Comment by mysticmind** [comment]
@erikljung Thanks for the fix 👍

**Comment by mysticmind** [comment]
@erikljung I will do a bug fix release shortly to Nuget

**Comment by mysticmind** [comment]
@erikljung  v1.2.0 is released to NuGet, it should be available for you to use once it gets indexed.

**Comment by erikljung** [comment]
Thank you!

**Pull request merged**
